version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: ./build_web/Dockerfile
      args:
        appname: my_app
        DATABASE_URL: ecto://my_app:my_app_pass@db/postgres
        # generate this from mix phx.gen.secret
        SECRET_KEY_BASE: ABCDABCD...
    ports:
      - "4000:4000"
    # command: tail -f /dev/null
    # stop_signal: SIGKILL
    # command: mix phx.server
    command: bin/my_app start
    env_file:
      - .env
    environment:
      - MIX_ENV=prod
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
volumes:
  db-data:
