version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: ./build_web/Dockerfile
      args:
        DATABASE_URL: ecto://postgres:postgres@db/my_app
        # generate this from mix phx.gen.secret
        SECRET_KEY_BASE: ABCDABCD...
        # set in .env
        APP_NAME: $APP_NAME
    restart: always
    env_file:
      - .env
    environment:
      - MIX_ENV=prod
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: bash -c "bin/$$APP_NAME start"
    # command: tail -f /dev/null
    # stop_signal: SIGKILL
    # command: mix phx.server
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
volumes:
  db-data:
